<Clock>:
    orientation: "vertical"

    Label:
        id: "clock"
        text: "--:--"

    BoxLayout:
        orientation: "horizontal"

        BoxLayout:
            orientation: "vertical"

            Label:
                text: "clock1"

            Label:
                text: "clock2"

        BoxLayout:
            orientation: "vertical"

            Label:
                text: "clock3"

            Label:
                text: "clock4"
